#!/usr/bin/env python3
"""Build, gzip, and embed the local UI without runtime network dependencies."""

from __future__ import annotations

import argparse
import gzip
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
OUTPUT = ROOT / "src" / "ui" / "embedded_assets.h"


def bytes_literal(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append("  " + ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16]))
    return ",\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--npm", default="npm")
    args = parser.parse_args()
    if not args.skip_build:
        npm = shutil.which(args.npm)
        if npm is None:
            raise SystemExit(f"npm executable not found: {args.npm}")
        subprocess.run([npm, "run", "build"], cwd=WEB, check=True)
    paths = [
        ("/index.html", "text/html; charset=utf-8", WEB / "dist" / "index.html", "INDEX_HTML"),
        ("/assets/app.js", "text/javascript; charset=utf-8", WEB / "dist" / "assets" / "app.js", "APP_JS"),
        ("/assets/style.css", "text/css; charset=utf-8", WEB / "dist" / "assets" / "style.css", "STYLE_CSS"),
    ]
    for _, _, path, _ in paths:
        if not path.is_file():
            raise SystemExit(f"missing built UI asset: {path}")
    sections = []
    assets = []
    for uri, content_type, path, symbol in paths:
        compressed = gzip.compress(path.read_bytes(), compresslevel=9, mtime=0)
        sections.append(
            f"inline constexpr std::uint8_t {symbol}_GZ[] PROGMEM = {{\n{bytes_literal(compressed)}\n}};"
        )
        assets.append(f'  {{"{uri}", "{content_type}", {symbol}_GZ, sizeof({symbol}_GZ)}}')
    header = """// Generated by tools/build_web.py. Do not hand edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <pgmspace.h>

namespace pm::ui {
struct Asset {
  const char* path;
  const char* content_type;
  const std::uint8_t* data;
  std::size_t size;
};

""" + "\n\n".join(sections) + "\n\ninline constexpr Asset ASSETS[] = {\n" + ",\n".join(assets) + "\n};\n\ninline const Asset* findAsset(const char* path) {\n  for (const auto& asset : ASSETS) {\n    if (std::strcmp(asset.path, path) == 0) return &asset;\n  }\n  return nullptr;\n}\n}  // namespace pm::ui\n"
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header, encoding="utf-8", newline="\n")
    total = sum(len(gzip.compress(path.read_bytes(), compresslevel=9, mtime=0)) for _, _, path, _ in paths)
    print(f"embedded 3 gzip assets ({total} bytes) into {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
