#!/usr/bin/env python3
"""Build, gzip, and embed the local UI without runtime network dependencies."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB = ROOT / "web"
OUTPUT = ROOT / "src" / "ui" / "embedded_assets.h"
GZIP_BUDGETS = {
    "INDEX_HTML": 4 * 1024,
    "APP_JS": 28 * 1024,
    "STYLE_CSS": 8 * 1024,
}
TOTAL_GZIP_BUDGET = 40 * 1024


def bytes_literal(data: bytes) -> str:
    rows = []
    for offset in range(0, len(data), 16):
        rows.append(
            "  " + ", ".join(f"0x{value:02x}" for value in data[offset : offset + 16])
        )
    return ",\n".join(rows)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-build", action="store_true")
    parser.add_argument("--npm", default="npm")
    args = parser.parse_args()
    if not args.skip_build:
        npm = shutil.which(args.npm)
        if npm is None:
            raise SystemExit(f"npm executable not found: {args.npm}")
        subprocess.run([npm, "run", "build"], cwd=WEB, check=True)
    paths = [
        (
            "/index.html",
            "text/html; charset=utf-8",
            WEB / "dist" / "index.html",
            "INDEX_HTML",
        ),
        (
            "/assets/app.js",
            "text/javascript; charset=utf-8",
            WEB / "dist" / "assets" / "app.js",
            "APP_JS",
        ),
        (
            "/assets/style.css",
            "text/css; charset=utf-8",
            WEB / "dist" / "assets" / "style.css",
            "STYLE_CSS",
        ),
    ]
    for _, _, path, _ in paths:
        if not path.is_file():
            raise SystemExit(f"missing built UI asset: {path}")
    index = paths[0][2].read_text(encoding="utf-8")
    for uri, _, path, _ in paths[1:]:
        revision = hashlib.sha256(path.read_bytes()).hexdigest()[:12]
        index = index.replace(uri, f"{uri}?v={revision}")
    payloads = {
        "INDEX_HTML": index.encode("utf-8"),
        "APP_JS": paths[1][2].read_bytes(),
        "STYLE_CSS": paths[2][2].read_bytes(),
    }
    compressed_payloads = {
        symbol: gzip.compress(payload, compresslevel=9, mtime=0)
        for symbol, payload in payloads.items()
    }
    for symbol, compressed in compressed_payloads.items():
        budget = GZIP_BUDGETS[symbol]
        print(
            f"{symbol.lower()}: raw={len(payloads[symbol])} gzip={len(compressed)} "
            f"budget={budget} sha256={hashlib.sha256(payloads[symbol]).hexdigest()}"
        )
        if len(compressed) > budget:
            raise SystemExit(
                f"{symbol} gzip size {len(compressed)} exceeds budget {budget}"
            )
    total = sum(len(payload) for payload in compressed_payloads.values())
    if total > TOTAL_GZIP_BUDGET:
        raise SystemExit(
            f"total gzip size {total} exceeds budget {TOTAL_GZIP_BUDGET}"
        )

    sections = []
    assets = []
    for uri, content_type, path, symbol in paths:
        compressed = compressed_payloads[symbol]
        digest = hashlib.sha256(payloads[symbol]).hexdigest()
        sections.append(
            f"inline constexpr std::uint8_t {symbol}_GZ[] PROGMEM = {{\n{bytes_literal(compressed)}\n}};"
        )
        assets.append(
            f'  {{"{uri}", "{content_type}", "{digest}", {symbol}_GZ, sizeof({symbol}_GZ)}}'
        )
    header = (
        """// Generated by tools/build_web.py. Do not hand edit.
#pragma once

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <pgmspace.h>

namespace pm::ui {
struct Asset {
  const char* path;
  const char* content_type;
  const char* sha256;
  const std::uint8_t* data;
  std::size_t size;
};

"""
        + "\n\n".join(sections)
        + "\n\ninline constexpr Asset ASSETS[] = {\n"
        + ",\n".join(assets)
        + "\n};\n\ninline const Asset* findAsset(const char* path) {\n  for (const auto& asset : ASSETS) {\n    if (std::strcmp(asset.path, path) == 0) return &asset;\n  }\n  return nullptr;\n}\n}  // namespace pm::ui\n"
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header, encoding="utf-8", newline="\n")
    print(
        f"embedded 3 gzip assets ({total}/{TOTAL_GZIP_BUDGET} bytes) "
        f"into {OUTPUT.relative_to(ROOT)}"
    )


if __name__ == "__main__":
    main()
